const yogaPoseAngles = {
    empty: {
        leftShoulder: 0,
        rightShoulder: 0,
        leftElbow: 0,
        rightElbow: 0, 
        leftWaist: 0,
        rightWaist: 0,
        leftKnee: 0,
        rightKnee: 0,
    },
    warrior1: {
        leftShoulder: 180,
        rightShoulder: 180,
        leftElbow: 180,
        rightElbow: 180, 
        leftWaist: 135,
        rightWaist: 90,
        leftKnee: 180,
        rightKnee: 90,
    },
    warrior2: {
        leftShoulder: 90,
        rightShoulder: 90,
        leftElbow: 180,
        rightElbow: 180, 
        leftWaist: 90,
        rightWaist: 135,
        leftKnee: 90,
        rightKnee: 180,
    },
    warrior3: {
        leftShoulder: 180,
        rightShoulder: 180,
        leftElbow: 180,
        rightElbow: 180, 
        leftWaist: 180,
        rightWaist: 90,
        leftKnee: 180,
        rightKnee: 180,
    },
    downwardFacingDog: {
        leftShoulder: 180,
        rightShoulder: 180,
        leftElbow: 180,
        rightElbow: 180, 
        leftWaist: 75,
        rightWaist: 75,
        leftKnee: 180,
        rightKnee: 180,
    },
    trianglePose: {
        leftShoulder: 90,
        rightShoulder: 70,
        leftElbow: 180,
        rightElbow: 180, 
        leftWaist: 130,
        rightWaist: 70,
        leftKnee: 180,
        rightKnee: 180,
    },
    reverseWarrior: {
        leftShoulder: 45,
        rightShoulder: 150,
        leftElbow: 180,
        rightElbow: 180, 
        leftWaist: 90,
        rightWaist: 120,
        leftKnee: 180,
        rightKnee: 90,
    },
    garlandPose: {
        leftShoulder: 60,
        rightShoulder: 60,
        leftElbow: 60,
        rightElbow: 60, 
        leftWaist: 15,
        rightWaist: 15,
        leftKnee: 25,
        rightKnee: 25,
    },
    halfForwardBend: {
        leftShoulder: 90,
        rightShoulder: 90,
        leftElbow: 180,
        rightElbow: 180, 
        leftWaist: 90,
        rightWaist: 90,
        leftKnee: 180,
        rightKnee: 180,
    },
    pyramidPose: {
        leftShoulder: 100,
        rightShoulder: 100,
        leftElbow: 130,
        rightElbow: 130, 
        leftWaist: 30,
        rightWaist: 90,
        leftKnee: 180,
        rightKnee: 180,
    },
    lowLungePosition: {
        leftShoulder: 60,
        rightShoulder: 60,
        leftElbow: 180,
        rightElbow: 180, 
        leftWaist: 15,
        rightWaist: 180,
        leftKnee: 90,
        rightKnee: 180,
    },
    treePose: {
        leftShoulder: 160,
        rightShoulder: 150,
        leftElbow: 180,
        rightElbow: 180, 
        leftWaist: 180,
        rightWaist: 120,
        leftKnee: 180,
        rightKnee: 30,
    },
    downwardFacingDogSplit: {
        leftShoulder: 160,
        rightShoulder: 160,
        leftElbow: 180,
        rightElbow: 180, 
        leftWaist: 90,
        rightWaist: 180,
        leftKnee: 180,
        rightKnee: 180,
    },
    plankPose: {
        leftShoulder: 75,
        rightShoulder: 75,
        leftElbow: 180,
        rightElbow: 180, 
        leftWaist: 180,
        rightWaist: 180,
        leftKnee: 180,
        rightKnee: 180,
    },
    bridgePose: {
        leftShoulder: 35,
        rightShoulder: 35,
        leftElbow: 180,
        rightElbow: 180, 
        leftWaist: 180,
        rightWaist: 180,
        leftKnee: 70,
        rightKnee: 70,
    },
    staffPose: {
        leftShoulder: 0,
        rightShoulder: 0,
        leftElbow: 180,
        rightElbow: 180, 
        leftWaist: 90,
        rightWaist: 90,
        leftKnee: 180,
        rightKnee: 180,
    },
    seatedForwardBend: {
        leftShoulder: 90,
        rightShoulder: 90,
        leftElbow: 180,
        rightElbow: 180, 
        leftWaist: 50,
        rightWaist: 50,
        leftKnee: 180,
        rightKnee: 180,
    },
    childsPose: {
        leftShoulder: 170,
        rightShoulder: 170,
        leftElbow: 180,
        rightElbow: 180, 
        leftWaist: 20,
        rightWaist: 20,
        leftKnee: 25,
        rightKnee: 25,
    },
};

const jointLandmarkNumbers = {
    leftShoulder: 11,
    rightShoulder: 12,
    leftElbow: 13,
    rightElbow: 14, 
    leftWaist: 23,
    rightWaist: 24,
    leftKnee: 25,
    rightKnee: 26,
};

const videoWidth = 640;
const videoHeight = 480;