const yogaPoseAngles = {
    warrior1: {
        angles: {
            leftShoulder: 180,
            rightShoulder: 180,
            leftElbow: 180,
            rightElbow: 180, 
            leftWaist: 135,
            rightWaist: 90,
            leftKnee: 180,
            rightKnee: 90,
        },
        imagePath: 'YogaImgs/Warrior1.jpg',
    },
    warrior2: {
        angles: {
            leftShoulder: 90,
            rightShoulder: 90,
            leftElbow: 180,
            rightElbow: 180, 
            leftWaist: 90,
            rightWaist: 135,
            leftKnee: 90,
            rightKnee: 180,
        },
        imagePath: 'YogaImgs/Warrior2.jpg',     
    },
    warrior3: {
        angles: {
            leftShoulder: 160,
            rightShoulder: 160,
            leftElbow: 180,
            rightElbow: 180, 
            leftWaist: 180,
            rightWaist: 90,
            leftKnee: 180,
            rightKnee: 180,
        },
        imagePath: 'YogaImgs/Warrior3.jpg',
    },
    downwardFacingDog: {
        angles: {
            leftShoulder: 180,
            rightShoulder: 180,
            leftElbow: 180,
            rightElbow: 180, 
            leftWaist: 75,
            rightWaist: 75,
            leftKnee: 180,
            rightKnee: 180,
        },
        imagePath: 'YogaImgs/DownwardFacingDog.jpg', 
    },
    trianglePose: {
        angles: {
            leftShoulder: 90,
            rightShoulder: 70,
            leftElbow: 180,
            rightElbow: 180, 
            leftWaist: 130,
            rightWaist: 70,
            leftKnee: 180,
            rightKnee: 180,
        },
        imagePath: 'YogaImgs/TrianglePose.jpg', 
    },
    reverseWarrior: {
        angles: {
            leftShoulder: 45,
            rightShoulder: 150,
            leftElbow: 180,
            rightElbow: 180, 
            leftWaist: 90,
            rightWaist: 120,
            leftKnee: 180,
            rightKnee: 90,
        },
        imagePath: 'YogaImgs/ReverseWarrior.jpg', 
    },
    garlandPose: {
        angles: {
            leftShoulder: 60,
            rightShoulder: 60,
            leftElbow: 60,
            rightElbow: 60, 
            leftWaist: 15,
            rightWaist: 15,
            leftKnee: 25,
            rightKnee: 25,
        },
        imagePath: 'YogaImgs/GarlandPose.jpg', 
    },
    halfForwardBend: {
        angles: {
            leftShoulder: 90,
            rightShoulder: 90,
            leftElbow: 180,
            rightElbow: 180, 
            leftWaist: 90,
            rightWaist: 90,
            leftKnee: 180,
            rightKnee: 180,
        },
        imagePath: 'YogaImgs/HalfForwardBend.jpg', 
    },
    pyramidPose: {
        angles: {
            leftShoulder: 100,
            rightShoulder: 100,
            leftElbow: 130,
            rightElbow: 130, 
            leftWaist: 30,
            rightWaist: 90,
            leftKnee: 180,
            rightKnee: 180,
        },
        imagePath: 'YogaImgs/PyramidPose.jpg', 
    },
    lowLungePosition: {
        angles: {
            leftShoulder: 60,
            rightShoulder: 60,
            leftElbow: 180,
            rightElbow: 180, 
            leftWaist: 15,
            rightWaist: 180,
            leftKnee: 90,
            rightKnee: 180,
        },
        imagePath: 'YogaImgs/LowLungePosition.jpg', 
    },
    treePose: {
        angles: {
            leftShoulder: 160,
            rightShoulder: 150,
            leftElbow: 180,
            rightElbow: 180, 
            leftWaist: 180,
            rightWaist: 120,
            leftKnee: 180,
            rightKnee: 30,
        },
        imagePath: 'YogaImgs/TreePose.jpg', 
    },
    downwardFacingDogSplit: {
        angles: {
            leftShoulder: 160,
            rightShoulder: 160,
            leftElbow: 180,
            rightElbow: 180, 
            leftWaist: 90,
            rightWaist: 180,
            leftKnee: 180,
            rightKnee: 180,
        },
        imagePath: 'YogaImgs/DownwardFacingDogSplit.jpg', 
    },
    plankPose: {
        angles: {
            leftShoulder: 75,
            rightShoulder: 75,
            leftElbow: 180,
            rightElbow: 180, 
            leftWaist: 180,
            rightWaist: 180,
            leftKnee: 180,
            rightKnee: 180,
        },
        imagePath: 'YogaImgs/PlankPose.jpg', 
    },
    bridgePose: {
        angles: {
            leftShoulder: 35,
            rightShoulder: 35,
            leftElbow: 180,
            rightElbow: 180, 
            leftWaist: 180,
            rightWaist: 180,
            leftKnee: 70,
            rightKnee: 70,
        },
        imagePath: 'YogaImgs/BridgePose.jpg', 
    },
    staffPose: {
        angles: {
            leftShoulder: 0,
            rightShoulder: 0,
            leftElbow: 180,
            rightElbow: 180, 
            leftWaist: 90,
            rightWaist: 90,
            leftKnee: 180,
            rightKnee: 180,
        },
        imagePath: 'YogaImgs/StaffPose.jpg', 
    },
    seatedForwardBend: {
        angles: {
            leftShoulder: 90,
            rightShoulder: 90,
            leftElbow: 180,
            rightElbow: 180, 
            leftWaist: 50,
            rightWaist: 50,
            leftKnee: 180,
            rightKnee: 180,
        },
        imagePath: 'YogaImgs/SeatedForwardBend.jpg', 
    },
    childsPose: {
        angles: {
            leftShoulder: 170,
            rightShoulder: 170,
            leftElbow: 180,
            rightElbow: 180, 
            leftWaist: 20,
            rightWaist: 20,
            leftKnee: 25,
            rightKnee: 25,
        },
        imagePath: 'YogaImgs/ChildsPose.jpg',
    },
};

const jointLandmarkNumbers = {
    leftShoulder: 11,
    rightShoulder: 12,
    leftElbow: 13,
    rightElbow: 14, 
    leftWaist: 23,
    rightWaist: 24,
    leftKnee: 25,
    rightKnee: 26,
};

const videoWidth = 640;
const videoHeight = 480;